
spring:
  datasource:
    url: jdbc:mysql://mysql-server:3306/microservice?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 111222
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL5Dialect

client:
  pseudo:
    property: Property from repo changed
